version: '1.0'

services:
  doctor-service:
      environment:
        DOCTOR_SERVICE_PASSWORD: $DOCTOR_SERVICE_PASSWORD
        MONGODB_PASSWORD: $MONGODB_PASSWORD
      build: doctor-service
      ports:
        - 7000:7000
      restart: always
      depends_on:
        config:
          condition: service_healthy
      logging:
        options:
          max-size: "10m"
          max-file: "10"

  doctor-mongodb:
      environment:
        MONGODB_PASSWORD: $MONGODB_PASSWORD
      build: mongodb
      ports:
        - 27000:27017
      restart: always
      logging:
        options:
          max-size: "10m"
          max-file: "10"

  drug-service:
      environment:
        DRUG_SERVICE_PASSWORD: $DRUG_SERVICE_PASSWORD
        MONGODB_PASSWORD: $MONGODB_PASSWORD
      build: drug-service
      ports:
        - 7500:7500
      restart: always
      depends_on:
        config:
          condition: service_healthy
      logging:
        options:
          max-size: "10m"
          max-file: "10"

  drug-mongodb:
      environment:
        MONGODB_PASSWORD: $MONGODB_PASSWORD
      build: mongodb
      ports:
        - 27500:27017
      restart: always
      logging:
        options:
          max-size: "10m"
          max-file: "10"

  patient-service:
      environment:
        PATIENT_SERVICE_PASSWORD: $PATIENT_SERVICE_PASSWORD
        MONGODB_PASSWORD: $MONGODB_PASSWORD
      build: patient-service
      ports:
        - 8000:8000
      restart: always
      depends_on:
        config:
          condition: service_healthy
      logging:
        options:
          max-size: "10m"
          max-file: "10"

  drug-mongodb:
      environment:
        MONGODB_PASSWORD: $MONGODB_PASSWORD
      build: mongodb
      ports:
        - 28000:27017
      restart: always
      logging:
        options:
          max-size: "10m"
          max-file: "10"