doctor-service:
 build: doctor-service
 ports:
  - 7000:7000
 links:
  - doctor-mongodb

doctor-mongodb:
 image: mongo

drug-service:
 build: drug-service
 ports:
  - 7500:7500
 links:
  - drug-mongodb

drug-mongodb:
 image: mongo

patient-service:
 build: patient-service
 ports:
  - 8000:8000
 links:
  - patient-mongodb

patient-mongodb:
 image: mongo