#!/usr/bin/env bash
export DOCTOR_SERVICE_PASSWORD="DOCTOR_SERVICE_PASSWORD"
export PATIENT_SERVICE_PASSWORD="PATIENT_SERVICE_PASSWORD"
export MONGODB_PASSWORD="MONGODB_PASSWORD"
export CONFIG_SERVICE_PASSWORD="CONFIG_SERVICE_PASSWORD"
docker-compose up