#!/usr/bin/env bash
export DOCTOR_SERVICE_PASSWORD="DOCTOR_SERVICE_PASSWORD"
export PATIENT_SERVICE_PASSWORD="PATIENT_SERVICE_PASSWORD"
export DRUG_SERVICE_PASSWORD="DRUG_SERVICE_PASSWORD"
export MONGODB_PASSWORD="MONGODB_PASSWORD"
docker-compose up