security:
  oauth2:
    client:
      clientId: appointment-service
      clientSecret: ${APPOINTMENT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: appointment-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: clinical-management
      port: 27017

server:
  context-path: /appointments
  port: 7500

weather:
  url: http://api.openweathermap.org/data/2.5/forecast
  id: 524901
  APPID: 9902aaf7af693bfa61bcf7e532f62e07