spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: clinical-management
      port: 27017

server:
  context-path: /uaa
  port: 5000

security:
  oauth2:
    resource:
      filter-order: 3