security:
  oauth2:
    client:
      clientId: doctor-service
      clientSecret: ${DOCTOR_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: doctor-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: clinical-management
      port: 27017

server:
  context-path: /doctors
  port: 7000

weather:
  url: http://api.openweathermap.org/data/2.5/forecast?id=524901&APPID=9902aaf7af693bfa61bcf7e532f62e07&units=metric