spring:
  data:
    mongodb:
      host: patient-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: clinical-management
      port: 27017

server:
  context-path: /patients
  port: 8000