security:
  oauth2:
    client:
      clientId: patient-service
      clientSecret: ${PATIENT_SERVICE_PASSWORD}
      accessTokenUri: http://doctor-service:7000/doctors/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: patient-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: clinical-management
      port: 27017

server:
  context-path: /patients
  port: 8000